# workflow to publish Blazor WASM app to GitHub Pages
name: DeployToGitHubPages

# environment variable & path to publish project to
env:
  PUBLISH_DIR: bin/Release/net5.0/publish/wwwroot

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install SDK & vsn
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    # publishes Release config (-c) of Blazor project
    - name: Publish app
      run: dotnet publish -c Release

    # rewrite module (index file must have base url tag, see more info:
    # https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0#github-pages
    - name: Rewrite base href
      uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
      with:
        html_path: ${{ env.PUBLISH_DIR }}/index.html
        base_href: /RockPaperScissors/

    # Runs a single command using the runners shell
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: master
        build_dir: ${{ env.PUBLISH_DIR }}
      env:
        GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}